/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IInterfacesIds,
  IInterfacesIdsInterface,
} from "../IInterfacesIds";

const _abi = [
  {
    inputs: [],
    name: "ids",
    outputs: [
      {
        internalType: "bytes4[]",
        name: "interfacesIds",
        type: "bytes4[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IInterfacesIds__factory {
  static readonly abi = _abi;
  static createInterface(): IInterfacesIdsInterface {
    return new utils.Interface(_abi) as IInterfacesIdsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInterfacesIds {
    return new Contract(address, _abi, signerOrProvider) as IInterfacesIds;
  }
}
