/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOpenNFTsV3, IOpenNFTsV3Interface } from "../IOpenNFTsV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenID",
        type: "uint256",
      },
    ],
    name: "burnNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "bool",
        name: "openMinting",
        type: "bool",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "minter",
        type: "address",
      },
      {
        internalType: "string",
        name: "jsonURI",
        type: "string",
      },
    ],
    name: "mintNFT",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenID",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOpenNFTsV3__factory {
  static readonly abi = _abi;
  static createInterface(): IOpenNFTsV3Interface {
    return new utils.Interface(_abi) as IOpenNFTsV3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOpenNFTsV3 {
    return new Contract(address, _abi, signerOrProvider) as IOpenNFTsV3;
  }
}
