/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IContractProbe,
  IContractProbeInterface,
} from "../IContractProbe";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "probe",
    outputs: [
      {
        internalType: "bool",
        name: "isContract",
        type: "bool",
      },
      {
        internalType: "address",
        name: "forwardedTo",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IContractProbe__factory {
  static readonly abi = _abi;
  static createInterface(): IContractProbeInterface {
    return new utils.Interface(_abi) as IContractProbeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContractProbe {
    return new Contract(address, _abi, signerOrProvider) as IContractProbe;
  }
}
