/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOpenNFTsV0, IOpenNFTsV0Interface } from "../IOpenNFTsV0";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "minter",
        type: "address",
      },
      {
        internalType: "string",
        name: "jsonURI",
        type: "string",
      },
    ],
    name: "addUser",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOpenNFTsV0__factory {
  static readonly abi = _abi;
  static createInterface(): IOpenNFTsV0Interface {
    return new utils.Interface(_abi) as IOpenNFTsV0Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOpenNFTsV0 {
    return new Contract(address, _abi, signerOrProvider) as IOpenNFTsV0;
  }
}
