[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
  "OpenNFTs=node_modules/OpenNFTs",
  "@openzeppelin=node_modules/@openzeppelin",
  "hardhat-deploy=node_modules/hardhat-deploy",
  "hardhat=node_modules/hardhat",
  "interfaces=contracts/interfaces",
  "interfacesNew=contracts/new/interfaces",
  "new=contracts/new",
  # "ds-test=lib/forge-std/lib/ds-test/src",
]
auto_detect_solc=true
# solc_version='0.8.9'


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
