@method = gasPrice
@urlEth = https://eth-mainnet.alchemyapi.io/v2/{{$dotenv ALCHEMY_API_KEY}}
@urlPol = https://polygon-mainnet.g.alchemy.com/v2/{{$dotenv ALCHEMY_API_KEY_POLYGON}}
@address = 0x981ab0D817710d8FFFC5693383C00D985A3BDa38

### getNFTs on mainnet from address without metadata
GET {{urlEth}}/getNFTs?owner={{address}}&withMetadata=false

### getNFTs on mainnet from address with metadata
GET {{urlEth}}/getNFTs?owner={{address}}

### getContractMetadata collection metadata 
GET {{urlEth}}/getContractMetadata?contractAddress=0xf6d53c7e96696391bb8e73be75629b37439938af


### getNFTs on polygon from address without metadata
GET {{urlPol}}/getNFTs?owner={{address}}&withMetadata=false

### getNFTs on polygon from address with metadata
GET {{urlPol}}/getNFTs?owner={{address}}


### getNFTs
https://eth-mainnet.alchemyapi.io/v2/{{$dotenv ALCHEMY_API_KEY}}/getNFTs?owner=0x981ab0D817710d8FFFC5693383C00D985A3BDa38&withMetadata=false

### getNFTs
https://polygon-mainnet.g.alchemy.com/v2/{{$dotenv ALCHEMY_API_KEY_POLYGON}}/getNFTs?owner=0x981ab0D817710d8FFFC5693383C00D985A3BDa38&withMetadata=false
