[profile.default]
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
cache_path = "cache"
fs_permissions = [
  { access = "read-write", path = "./addresses.json" },
  { access = "read-write", path = "./out" },
]

[fmt]
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
linea = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
avalanche = "https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_BASE}"
polygon-zkevm = "https://zkevm-rpc.com"
gnosis = "https://rpc.ankr.com/gnosis"
fantom = "https://rpc.ankr.com/fantom"
bsc = "https://rpc.ankr.com/bsc"
scroll = "https://rpc.scroll.io"
pgn = "https://rpc.publicgoods.network"
zora = "https://rpc.zora.energy"
mantle = "https://rpc.ankr.com/mantle"
mode = "https://mainnet.mode.network"
manta-pacific = "https://pacific-rpc.manta.network/http"
blast = "https://blast-mainnet.infura.io/v3/${INFURA_API_KEY}"
celo = "https://forno.celo.org"
skale-calypso = "https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague"

# TESTNETS
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
amoy = "https://polygon-amoy.infura.io/v3/${INFURA_API_KEY}"
optimism-sepolia = "https://optimism-sepolia.infura.io/v3/${INFURA_API_KEY}"
arbitrum-sepolia = "https://arbitrum-sepolia.infura.io/v3/${INFURA_API_KEY}"
fuji = "https://avalanche-fuji.infura.io/v3/${INFURA_API_KEY}"
blast-sepolia = "https://blast-sepolia.infura.io/v3/${INFURA_API_KEY}"
celo-alfajores = "https://celo-alfajores.infura.io/v3/${INFURA_API_KEY}"

bsc-testnet = "https://bsc-testnet-rpc.publicnode.com"
holesky = "https://ethereum-holesky.publicnode.com"
base-sepolia = "https://sepolia.base.org/"
linea-goerli = "https://rpc.goerli.linea.build/"
linea-sepolia = "https://rpc.sepolia.linea.build/"
telos-testnet = "https://testnet.telos.net/evm"
chiado = "https://rpc.chiadochain.net"
polygon-zkevm-testnet = "https://rpc.public.zkevm-test.net"
polygon-zkevm-cardona = "https://rpc.cardona.zkevm-rpc.com"
scroll-alpha-testnet = "https://alpha-rpc.scroll.io/l2"
scroll-sepolia = "https://sepolia-rpc.scroll.io/"
pgn-sepolia = "https://sepolia.publicgoods.network"
zora-goerli = "https://testnet.rpc.zora.co"
zora-sepolia = "https://sepolia.rpc.zora.energy"
mantle-testnet = "https://rpc.testnet.mantle.xyz"
mode-sepolia = "https://sepolia.mode.network"
manta-pacific-testnet = "https://pacific-rpc.testnet.manta.network/http"
chaos-testnet = "https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"
calypso-testnet = "https://testnet.skalenodes.com/v1/giant-half-dual-testnet"
taiko-katla = "https://rpc.katla.taiko.xyz"
fantom-testnet = "https://rpc.ankr.com/fantom_testnet"

anvil = "http://127.0.0.1:8545"

[etherscan]
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }
polygon-zkevm =  { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }
linea = { key = "${ETHERSCAN_API_KEY_LINEA}" }

# TESTNETS
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}", url = "https://api-holesky.etherscan.io/api" }
calypso-testnet = { key = "non-applicable", url = "https://giant-half-dual-testnet.explorer.testnet.skalenodes.com" }

linea-testnet = { key = "${ETHERSCAN_API_KEY_LINEA}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY_BASE}" }
chiado = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }
polygon-zkevm-testnet =  { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }

#


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
