[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
auto_detect_solc=true

[fmt]
number_underscore = 'thousands'

[rpc_endpoints]
# mainnet = "${MAINNET_RPC_URL}"
# goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
