[profile.default]
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
cache_path  = "cache-forge"
fs_permissions = [{ access = "read-write", path = "./"}]


[fmt]
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
matic = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism = "https://rpc.ankr.com/optimism"
polygonzkevm = "https://zkevm-rpc.com"
gnosis = "https://rpc.ankr.com/gnosis"
avalanche = "https://rpc.ankr.com/avalanche"
fantom = "https://rpc.ankr.com/fantom"
bsc = "https://rpc.ankr.com/bsc"

sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"



telostestnet = "https://testnet.telos.net/evm"
anvil = "http://127.0.0.1:8545"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
