[profile.default]
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
cache_path = "cache-forge"
fs_permissions = [{ access = "read-write", path = "./" }]


[fmt]
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
matic = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism = "https://rpc.ankr.com/optimism"
base = "https://base.gateway.tenderly.co"
polygonzkevm = "https://zkevm-rpc.com"
gnosis = "https://rpc.ankr.com/gnosis"
avalanche = "https://rpc.ankr.com/avalanche"
fantom = "https://rpc.ankr.com/fantom"
bsc = "https://rpc.ankr.com/bsc"

# TESTNETS
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
base-goerli = "https://goerli.base.org/"
chiado = "https://rpc.chiadochain.net"
telostestnet = "https://testnet.telos.net/evm"
local = "http://127.0.0.1:8545"

[etherscan]
gnosis =  { key = "${ETHERSCAN_API_KEY_GNOSIS}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }

# TESTNETS
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base-goerli = { key = "${ETHERSCAN_API_KEY_BASE}" }
chiado =  { key = "${ETHERSCAN_API_KEY_GNOSIS}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
