[profile.default]
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
cache_path = "cache-forge"
fs_permissions = [{ access = "read-write", path = "./" }]


[fmt]
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
matic = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism = "https://rpc.ankr.com/optimism"
base = "https://base.gateway.tenderly.co"
polygon-zkevm = "https://zkevm-rpc.com"
gnosis = "https://rpc.ankr.com/gnosis"
avalanche = "https://rpc.ankr.com/avalanche"
fantom = "https://rpc.ankr.com/fantom"
bsc = "https://rpc.ankr.com/bsc"
scroll = "https://rpc.scroll.io"
linea = "https://rpc.linea.build/"
pgn = "https://rpc.publicgoods.network"
zora = "https://rpc.zora.energy"
mantle = "https://rpc.ankr.com/mantle"

# TESTNETS
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
holesky = "https://ethereum-holesky.publicnode.com"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
base-goerli = "https://goerli.base.org/"
linea-testnet = "https://rpc.goerli.linea.build/"
telos-testnet = "https://testnet.telos.net/evm"
chiado = "https://rpc.chiadochain.net"
local = "http://127.0.0.1:8545"
polygon-zkevm-testnet = "https://rpc.public.zkevm-test.net"
scroll-alpha-testnet = "https://alpha-rpc.scroll.io/l2"
scroll-sepolia = "https://sepolia-rpc.scroll.io/"
pgn-sepolia = "https://sepolia.publicgoods.network"
zora-goerli = "https://testnet.rpc.zora.co"
mantle-testnet = "https://rpc.testnet.mantle.xyz"

[etherscan]
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }
polygon-zkevm =  { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }
linea = { key = "${ETHERSCAN_API_KEY_LINEA}" }

# TESTNETS
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}", url = "https://api-holesky.etherscan.io/api" }

linea-testnet = { key = "${ETHERSCAN_API_KEY_LINEA}" }
base-goerli = { key = "${ETHERSCAN_API_KEY_BASE}" }
chiado = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }
polygon-zkevm-testnet =  { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }

#


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
