[profile.default]
src = "src"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.17"
cache_path  = "cache-forge"
fs_permissions = [{ access = "read", path = "./"}]


[fmt]
number_underscore = "thousands"

[rpc_endpoints]
# mainnet = "${MAINNET_RPC_URL}"
# goerli = "${GOERLI_RPC_URL}"
#matic = "${MATIC_RPC_URL}"
telostestnet = "https://testnet.telos.net/evm"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
