/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IContractProbeInterface extends utils.Interface {
  contractName: "IContractProbe";
  functions: {
    "probe(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "probe", values: [string]): string;

  decodeFunctionResult(functionFragment: "probe", data: BytesLike): Result;

  events: {};
}

export interface IContractProbe extends BaseContract {
  contractName: "IContractProbe";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IContractProbeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    probe(
      addr: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { isContract: boolean; forwardedTo: string }
    >;
  };

  probe(
    addr: string,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { isContract: boolean; forwardedTo: string }>;

  callStatic: {
    probe(
      addr: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { isContract: boolean; forwardedTo: string }
    >;
  };

  filters: {};

  estimateGas: {
    probe(addr: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    probe(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
