name: DEPLOY wp plugin
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy Plugin to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.18.2
          run_install: true

      - name: Build wp plugin
        run: pnpm build-wp-plugin
        env:
          ENVIR: PROD
          NODE_DEBUG: false
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ALCHEMY_API_KEY_POLYGON: ${{ secrets.ALCHEMY_API_KEY_POLYGON }}
          ALCHEMY_API_KEY_ARBITRUM: ${{ secrets.ALCHEMY_API_KEY_ARBITRUM }}
          ALCHEMY_API_KEY_OPTIMISM: ${{ secrets.ALCHEMY_API_KEY_OPTIMISM }}
          COVALENT_API_KEY: ${{ secrets.COVALENT_API_KEY }}
          NFT_STORAGE_KEY: ${{ secrets.NFT_STORAGE_KEY }}

      - name: Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: wordpress/plugins/kredeum-nfts/
          ASSETS_DIR: wordpress/assets
          SLUG: kredeum-nfts
