name: DEPLOY dapp
on:
  push:
    branches:
      - deployWithGitHubAction

jobs:
  check:
    name: Build dapp, ready to be deployed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.1
          
      - name: Build dapp
        run: pnpm build-dapp
        env:
          ENVIR: PROD
          NODE_DEBUG: false
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ALCHEMY_API_KEY_POLYGON: ${{ secrets.ALCHEMY_API_KEY_POLYGON }}
          ALCHEMY_API_KEY_ARBITRUM: ${{ secrets.ALCHEMY_API_KEY_ARBITRUM }}
          ALCHEMY_API_KEY_OPTIMISM: ${{ secrets.ALCHEMY_API_KEY_OPTIMISM }}
          COVALENT_API_KEY: ${{ secrets.COVALENT_API_KEY }}
          NFT_STORAGE_KEY: ${{ secrets.NFT_STORAGE_KEY }}

      - name: Delete .gitignore to include web/dapp in commit
        run: rm web/.gitignore

      - name: Commit Dapp build
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add web/dapp
          git commit -am "${{ github.ref_name }} dapp build !"

      - name: Push Dapp build
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build/${{ github.ref_name }}
          force: true
          directory: "web/dapp"
