name: TEST forge

on: push

jobs:
  check:
    name: Test smartcontracts with forge
    runs-on: ubuntu-22.04

    steps:
      - name: CHECKOUT kredeum nfts

        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: INSTALL foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: BUILD forge
        working-directory: contracts
        run: forge build

      - name: TEST forge
        working-directory: contracts
        run: forge test -vvv
